name: Update exes
on:
  push:
    paths:
      - 'exe/**'
    branches-ignore:
      - main
      - pages

defaults:
  run:
    shell: cmd

jobs:
  update:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            winapi:
              - 'exe/winapi/**'
            zip:
              - 'exe/zip/**'

      - name: winapi
        if: steps.filter.outputs.winapi == 'true'
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\vsdevcmd.bat"
          cd exe\winapi
          call build.bat

      - name: zip
        if: steps.filter.outputs.zip == 'true'
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\vsdevcmd.bat"
          cd exe\zip
          call build.bat

      - name: Add results to PR
        run: |
          git config user.name "GitHub action"
          git config user.email "bot@github.com"
          git add exe
          git commit -m "update from CI"
          git push
