name: check formatting
on: [push]
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache dprint
        uses: actions/cache@v4
        with:
          path: |
            ~/.dprint
            ~/.cache/dprint
          key: dprint

      - name: Install dprint
        run: |
          if [ ! -f $HOME/.dprint/bin/dprint ]; then
            curl -fsSL https://dprint.dev/install.sh | sh
          fi
          echo $HOME/.dprint/bin >> $GITHUB_PATH

      - run: ./misc/fmt.sh --check
